const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('production/app.js','utf8').replace(/\(async\(\)=>\{save\(session\);[\s\S]*?\}\)\(\);/,'');
function app(storage='null'){
 const elements=new Map(),requests=[];
 const el=id=>{if(!elements.has(id))elements.set(id,{value:id==='km'?'500000':'',innerHTML:'',textContent:'',className:'',disabled:false,files:[],style:{},classList:{add(){},remove(){},contains(){return false}},replaceChildren(){this.innerHTML=''},focus(){},querySelectorAll(){return []},reportValidity(){return true}});return elements.get(id)};
 const context=vm.createContext({URLSearchParams,AbortSignal,Date,Math,Number,String,JSON,Set,Array,Object,encodeURIComponent,crypto:require('node:crypto').webcrypto,localStorage:{getItem(){return storage},setItem(){},removeItem(){}},document:{getElementById:el,querySelectorAll(){return []},addEventListener(){},body:{style:{}},activeElement:null},window:{addEventListener(){}},location:{origin:'https://example.invalid',pathname:'/',hash:''},history:{replaceState(){}},console,alert(){},setTimeout,fetch:async(url,opt)=>{requests.push({url,opt});return {ok:true,json:async()=>[]}}});vm.runInContext(source,context);return {el,context,requests,run:code=>vm.runInContext(code,context)};
}
test('malformed local session cannot break page initialization',()=>{const a=app('{bad');assert.equal(a.run('session'),null);assert.match(a.el('make').innerHTML,/Porsche/)});
test('user text is escaped in cards, detail and admin user list',async()=>{const a=app();a.context.fixture={id:'20000000-0000-4000-8000-000000000001',year:2020,make:'<img src=x onerror=alert(1)>',model:'"<svg onload=alert(1)>',city:'<script>bad</script>',description:'<img onerror=evil>',fuel:'Gasoline',price:12000,mileage:10000,images:[],seller_phone:'123" onclick="evil',seller_email:'a" onclick="evil'};a.run('cars=[fixture];render(cars)');assert.ok(!a.el('cards').innerHTML.includes('<svg'));assert.match(a.el('cards').innerHTML,/&lt;img/);await a.run('detail(fixture.id)');assert.ok(!a.el('modal').innerHTML.includes('<script>'));assert.ok(!a.el('modal').innerHTML.includes(' onclick="evil'));assert.match(a.run('renderAdminUsers([{user_id:fixture.id,display_name:fixture.make,email:fixture.model}])'),/&lt;img/)});
test('make selection populates Porsche model dropdown',()=>{const a=app();a.el('make').value='Porsche';a.el('make').onchange();assert.match(a.el('model').innerHTML,/911/);assert.match(a.el('model').innerHTML,/Taycan/)});
test('invalid filter range is rejected before network request',async()=>{const a=app();a.el('pmin').value='10000';a.el('pmax').value='500';await a.run('load()');assert.equal(a.requests.length,0);assert.match(a.el('count').textContent,/range/)});
test('browse uses bounded keyset pagination and encoded filters',async()=>{const a=app();a.el('make').value='Alfa Romeo';await a.run('load(0)');assert.match(a.requests[0].url,/limit=25/);assert.ok(!a.requests[0].url.includes('offset='));assert.match(a.requests[0].url,/make=eq.Alfa%20Romeo/)});
test('favorites query is independent of current search',async()=>{const a=app();a.el('make').value='Porsche';a.run('session={access_token:"test",user:{id:"10000000-0000-4000-8000-000000000001"}}');await a.run('favorites()');assert.match(a.requests[0].url,/favorites\?select=listings!inner/);assert.ok(!a.requests[0].url.includes('make='))});
test('no file and invalid file type are rejected before listing creation',async()=>{const a=app();await a.run('postCar({preventDefault(){}})');assert.equal(a.requests.length,0);assert.match(a.el('smsg').innerHTML,/1–8/);a.el('si').files=[{type:'text/html',size:200}];await a.run('postCar({preventDefault(){}})');assert.equal(a.requests.length,0);assert.match(a.el('smsg').innerHTML,/JPEG/)});
test('failed image upload deletes pending listing without exposing it',async()=>{const a=app();a.run('session={access_token:"test",user:{id:"10000000-0000-4000-8000-000000000001",email:"test@example.invalid"}}');a.el('si').files=[{type:'image/jpeg',size:200}];a.el('se').value='test@example.invalid';a.context.fetch=async(url,opt)=>{a.requests.push({url,opt});if(opt.method==='POST'&&url.includes('/rest/v1/listings'))return{ok:true,json:async()=>[{id:'20000000-0000-4000-8000-000000000001'}]};if(url.includes('/storage/'))return{ok:false,json:async()=>({message:'Upload failed'})};return{ok:true,json:async()=>null}};await a.run('postCar({preventDefault(){}})');assert.equal(JSON.parse(a.requests[0].opt.body).status,'pending');assert.ok(a.requests.some(r=>r.opt.method==='DELETE'&&r.url.includes('/listings?id=')));assert.match(a.el('smsg').innerHTML,/Upload failed/)});
test('successful submission stays pending and prevents duplicate submit',async()=>{const a=app();a.run('session={access_token:"test",user:{id:"10000000-0000-4000-8000-000000000001",email:"test@example.invalid"}}');a.el('si').files=[{type:'image/jpeg',size:200}];a.el('se').value='test@example.invalid';a.context.fetch=async(url,opt)=>{a.requests.push({url,opt});return{ok:true,json:async()=>opt.method==='POST'&&url.endsWith('/listings')?[{id:'20000000-0000-4000-8000-000000000001'}]:[]}};await a.run('postCar({preventDefault(){}})');assert.equal(JSON.parse(a.requests[0].opt.body).status,'pending');assert.equal(a.el('post').disabled,true);assert.match(a.el('smsg').innerHTML,/admin approval/)});
test('recovery callback validates token before showing password form',async()=>{const a=app();a.context.location.hash='#access_token=test&refresh_token=test&type=recovery&expires_in=3600';a.context.fetch=async(url,opt)=>{a.requests.push({url,opt});return{ok:true,json:async()=>url.endsWith('/auth/v1/user')?{id:'10000000-0000-4000-8000-000000000001',email:'test@example.invalid'}:[]}};await a.run('authCallback()');assert.match(a.requests[0].url,/auth\/v1\/user/);assert.match(a.el('modal').innerHTML,/Choose a new password/)});
test('recovery password confirmation mismatch makes no network call',async()=>{const a=app();a.el('rp').value='different-one';a.el('rp2').value='different-two';await a.run('updatePassword()');assert.equal(a.requests.length,0);assert.match(a.el('rmsg').textContent,/match/)});
test('mobile account contains sign out and every inline handler parses',async()=>{const a=app();a.run('session={access_token:"test",user:{id:"10000000-0000-4000-8000-000000000001",email:"test@example.invalid"}}');await a.run('account()');assert.match(a.el('modal').innerHTML,/onclick="signout\(\)"/);const html=fs.readFileSync('production/index.html','utf8')+a.el('modal').innerHTML;for(const m of html.matchAll(/\bon\w+="([^"]*)"/g))new vm.Script('(function(event){'+m[1]+'})')});
