const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('production/telegram.js','utf8');
function setup({search='',hash='',telegram=false}={}){
 const calls=[],listeners={},classes=new Set(),styles={},buttons=[],modalClasses=new Set();
 const sdk={platform:telegram?'ios':'unknown',initData:telegram?'signed-payload':'',initDataUnsafe:{},safeAreaInset:{top:20,bottom:10},contentSafeAreaInset:{top:40,bottom:0},viewportStableHeight:700,isVersionAtLeast:()=>true,ready(){calls.push('ready')},expand(){calls.push('expand')},setHeaderColor(){},setBackgroundColor(){},setBottomBarColor(){},onEvent(){},BackButton:{onClick(fn){this.handler=fn},show(){calls.push('back-show')},hide(){calls.push('back-hide')}},disableClosingConfirmation(){},enableClosingConfirmation(){calls.push('confirm-close')},openTelegramLink(url){calls.push(url)},HapticFeedback:{selectionChanged(){}}};
 const modal={querySelector(){return null}};
 const ctx={URLSearchParams,location:{origin:'https://p2pcars-alberta.vercel.app',search,hash},document:{getElementById:id=>id==='mbg'?{classList:{contains:c=>modalClasses.has(c)}}:id==='modal'?modal:null,documentElement:{classList:{add:c=>classes.add(c)},style:{setProperty:(k,v)=>styles[k]=v}},addEventListener:(name,fn)=>listeners[name]=fn,querySelector(){return {}},createElement(){return {}},head:{appendChild(s){calls.push(s.src)}}},window:{...(telegram?{Telegram:{WebApp:sdk}}:{}),alert(){},prompt(){}},navigator:{clipboard:{async writeText(url){calls.push(url)}}},view:'home',detail(id){calls.push('detail:'+id)},closeM(){modalClasses.delete('show');calls.push('closed')},home(){ctx.view='home';calls.push('home')},nav(){},encodeURIComponent,Number,Math};
 vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,calls,classes,styles,sdk,modalClasses,listeners};
}
test('ordinary browser keeps existing UI and does not load Telegram SDK',()=>{const a=setup();a.ctx.window.P2PTelegram.appReady();assert.equal(a.classes.size,0);assert.equal(a.calls.length,0)});
test('miniapp browser preview works without SDK or Telegram credentials',()=>{const a=setup({search:'?miniapp=1'});assert.ok(a.classes.has('miniapp'));assert.ok(a.calls.includes('https://telegram.org/js/telegram-web-app.js'));a.ctx.window.P2PTelegram.appReady();assert.ok(!a.calls.includes('ready'))});
test('Telegram initializes native controls and safe insets',()=>{const a=setup({telegram:true});assert.ok(a.classes.has('miniapp'));assert.ok(a.calls.includes('ready'));assert.ok(a.calls.includes('expand'));assert.equal(a.styles['--p2p-safe-top'],'60px');assert.equal(a.styles['--p2p-viewport-height'],'700px')});
test('native back closes modal first then returns from favorites to home',()=>{const a=setup({telegram:true});a.modalClasses.add('show');a.ctx.window.P2PTelegram.syncNavigation();assert.equal(a.calls.at(-1),'back-show');a.sdk.BackButton.handler();assert.ok(a.calls.includes('closed'));a.ctx.view='fav';a.sdk.BackButton.handler();assert.ok(a.calls.includes('home'));assert.equal(a.calls.at(-1),'back-hide')});
test('launch listing opens once after app is ready and rejects injected IDs',()=>{const id='20000000-0000-4000-8000-000000000001';const a=setup({telegram:true});a.sdk.initDataUnsafe.start_param='car_'+id;a.ctx.window.P2PTelegram.appReady();a.ctx.window.P2PTelegram.appReady();assert.deepEqual(a.calls.filter(x=>x.startsWith('detail:')),['detail:'+id]);const bad=setup({search:'?listing=bad%26status%3Deq.pending'});bad.ctx.window.P2PTelegram.appReady();assert.equal(bad.calls.length,0)});
test('browser listing links and Telegram shares retain the exact public ID',async()=>{const id='20000000-0000-4000-8000-000000000001';const a=setup({search:'?listing='+id});a.ctx.window.P2PTelegram.appReady();assert.ok(a.calls.includes('detail:'+id));await a.ctx.window.P2PTelegram.shareListing(id,'Toyota');assert.ok(a.calls.includes('https://p2pcars-alberta.vercel.app/?listing='+id));const b=setup({telegram:true});await b.ctx.window.P2PTelegram.shareListing(id,'Toyota');assert.match(b.calls.at(-1),/P2pcarsalbertabot%3Fstartapp%3Dcar_/);assert.ok(b.calls.at(-1).includes(id))});
test('both deploy configurations allow only Telegram framing and official SDK',()=>{for(const path of ['vercel.json','production/vercel.json']){const c=JSON.parse(fs.readFileSync(path));const h=c.headers[0].headers;assert.ok(!h.some(x=>x.key==='X-Frame-Options'));const policy=h.find(x=>x.key==='Content-Security-Policy').value;assert.match(policy,/script-src[^;]+https:\/\/telegram.org/);assert.match(policy,/frame-ancestors 'self' https:\/\/web.telegram.org https:\/\/\*\.web.telegram.org;/);assert.ok(!policy.includes("frame-ancestors *"));}});
