
const URL="https://rjoipowznfokhvahuozf.supabase.co",KEY="sb_publishable_J9fxpOkaIxvgEsTJ2IwHrw_7exploAN",makes={
  Acura: ["Integra","ILX","TL","TLX","TSX","RDX","MDX","ZDX"],
  "Alfa Romeo": ["Giulia","Stelvio","Tonale","4C"],
  "Aston Martin": ["Vantage","DB11","DB12","DBX"],
  Audi: ["A3","A4","A5","A6","A7","A8","S3","S4","S5","Q3","Q4 e-tron","Q5","Q7","Q8","e-tron","RS 3","RS 5","RS 6"],
  Bentley: ["Bentayga","Continental GT","Flying Spur"],
  BMW: ["2 Series","3 Series","4 Series","5 Series","7 Series","8 Series","X1","X2","X3","X4","X5","X6","X7","Z4","i3","i4","i5","i7","iX"],
  Buick: ["Encore","Encore GX","Envision","Enclave","Regal","LaCrosse"],
  Cadillac: ["ATS","CTS","CT4","CT5","XT4","XT5","XT6","Escalade","Lyriq"],
  Chevrolet: ["Cruze","Malibu","Impala","Trax","Trailblazer","Equinox","Blazer","Traverse","Tahoe","Suburban","Colorado","Silverado 1500","Silverado 2500HD","Camaro","Corvette","Bolt EV","Bolt EUV"],
  Chrysler: ["200","300","Pacifica","Town & Country"],
  Dodge: ["Dart","Challenger","Charger","Journey","Durango","Grand Caravan","Hornet"],
  Ferrari: ["Roma","Portofino","California","488","F8 Tributo","296 GTB","SF90"],
  Fiat: ["500","500X","500L","124 Spider"],
  Ford: ["Fiesta","Focus","Fusion","Escape","Edge","Explorer","Expedition","Bronco","Bronco Sport","EcoSport","Maverick","Ranger","F-150","F-150 Lightning","F-250","F-350","Mustang","Mustang Mach-E","Transit"],
  Genesis: ["G70","G80","G90","GV60","GV70","GV80"],
  GMC: ["Terrain","Acadia","Yukon","Yukon XL","Canyon","Sierra 1500","Sierra 2500HD","Sierra 3500HD","Hummer EV"],
  Honda: ["Fit","Civic","Accord","Insight","HR-V","CR-V","Passport","Pilot","Ridgeline","Odyssey"],
  Hummer: ["H2","H3"],
  Hyundai: ["Accent","Elantra","Sonata","Venue","Kona","Tucson","Santa Fe","Palisade","Santa Cruz","Ioniq","Ioniq 5","Ioniq 6"],
  Infiniti: ["Q50","Q60","QX30","QX50","QX55","QX60","QX80"],
  Jaguar: ["XE","XF","XJ","F-Type","F-Pace","E-Pace","I-Pace"],
  Jeep: ["Renegade","Compass","Cherokee","Grand Cherokee","Wrangler","Gladiator","Wagoneer","Grand Wagoneer"],
  Kia: ["Rio","Forte","K4","K5","Soul","Niro","Seltos","Sportage","Sorento","Telluride","Carnival","Stinger","EV6","EV9"],
  Lamborghini: ["Huracan","Aventador","Urus","Revuelto"],
  "Land Rover": ["Discovery Sport","Discovery","Defender","Range Rover Evoque","Range Rover Velar","Range Rover Sport","Range Rover"],
  Lexus: ["IS","ES","GS","LS","RC","LC","UX","NX","RX","GX","LX","RZ"],
  Lincoln: ["MKC","MKX","Corsair","Nautilus","Aviator","Navigator"],
  Lucid: ["Air","Gravity"],
  Maserati: ["Ghibli","Quattroporte","Levante","Grecale","GranTurismo"],
  Mazda: ["Mazda2","Mazda3","Mazda6","CX-3","CX-30","CX-5","CX-50","CX-70","CX-9","CX-90","MX-5"],
  "Mercedes-Benz": ["A-Class","B-Class","C-Class","E-Class","S-Class","CLA","CLS","GLA","GLB","GLC","GLE","GLS","G-Class","AMG GT","EQA","EQB","EQE","EQS"],
  MINI: ["Cooper","Cooper S","Clubman","Countryman"],
  Mitsubishi: ["Lancer","Mirage","RVR","Eclipse Cross","Outlander","Outlander PHEV"],
  Nissan: ["Micra","Versa","Sentra","Altima","Maxima","Kicks","Qashqai","Rogue","Murano","Pathfinder","Armada","Frontier","Titan","370Z","Z","Leaf","Ariya"],
  Polestar: ["Polestar 2","Polestar 3","Polestar 4"],
  Pontiac: ["G5","G6","Grand Prix","Vibe","Solstice"],
  Porsche: ["718 Boxster","718 Cayman","911","Panamera","Macan","Cayenne","Taycan"],
  Ram: ["1500","1500 Classic","2500","3500","ProMaster","ProMaster City"],
  Rivian: ["R1T","R1S"],
  "Rolls-Royce": ["Ghost","Phantom","Cullinan","Wraith"],
  Saab: ["9-3","9-5","9-7X"],
  Saturn: ["Astra","Aura","Ion","Outlook","Vue"],
  Scion: ["FR-S","iM","tC","xB","xD"],
  smart: ["fortwo"],
  Subaru: ["Impreza","Legacy","WRX","Crosstrek","Forester","Outback","Ascent","BRZ","Solterra"],
  Suzuki: ["Grand Vitara","Kizashi","SX4","Swift"],
  Tesla: ["Model 3","Model Y","Model S","Model X","Cybertruck"],
  Toyota: ["Yaris","Corolla","Camry","Avalon","Prius","Crown","Corolla Cross","C-HR","RAV4","Venza","Highlander","Grand Highlander","4Runner","Land Cruiser","Sequoia","Tacoma","Tundra","Sienna","GR86","Supra","bZ4X"],
  Volkswagen: ["Jetta","Passat","Arteon","Golf","Golf GTI","Golf R","Taos","Tiguan","Atlas","Atlas Cross Sport","ID.4","ID. Buzz"],
  Volvo: ["S60","S90","V60","V90","XC40","XC60","XC90","C40 Recharge","EX30","EX90"]
};
const $=id=>document.getElementById(id);let session=readSession(),cars=[],favSet=new Set(),view="home",isAdmin=false;
$("make").innerHTML='<option value="">Make</option>'+Object.keys(makes).sort().map(x=>'<option>'+x+'</option>').join("");$("make").onchange=()=>{$("model").innerHTML='<option value="">Model</option>'+((makes[$("make").value]||[]).map(x=>'<option>'+x+'</option>').join(""))};$("km").oninput=()=>{$("kmLabel").textContent=+$("km").value>=500000?"500,000+ km":(+$("km").value).toLocaleString()+" km"};
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function readSession(){try{const s=JSON.parse(localStorage.getItem("roadora_session")||"null");return s?.access_token&&s?.user?.id?s:null}catch{return null}}
function message(id,text,ok=false){const el=$(id);if(el){el.className="msg "+(ok?"ok":"err");el.textContent=text}}
function headers(user=false){const h={apikey:KEY,"Content-Type":"application/json"};if(user&&session?.access_token)h.Authorization="Bearer "+session.access_token;return h}async function req(path,opt={}){
 if(opt.headers?.Authorization && !path.startsWith('/auth/') && session?.expires_at<Date.now()/1000+60){await refreshSession();opt.headers={...opt.headers,...headers(true)}}
 const r=await fetch(URL+path,{...opt,signal:opt.signal||AbortSignal.timeout(30000)});let j=null;try{j=await r.json()}catch{}
 if(!r.ok)throw new Error(j?.msg||j?.message||j?.error_description||j?.error||("HTTP "+r.status));return j
}
function save(s){session=s;isAdmin=false;try{if(s)localStorage.setItem("roadora_session",JSON.stringify(s));else localStorage.removeItem("roadora_session")}catch{}$("authBtn").textContent=s?"Sign out":"Sign in"}
let refreshing=null;
async function refreshSession(){if(!session?.refresh_token)return;if(refreshing)return refreshing;refreshing=(async()=>{try{const d=await req("/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:headers(false),body:JSON.stringify({refresh_token:session.refresh_token})});save({...d,expires_at:Math.floor(Date.now()/1000)+d.expires_in})}catch(e){if(/invalid|expired|refresh token/i.test(e.message))save(null);throw e}finally{refreshing=null}})();return refreshing}
async function signout(){try{await req('/auth/v1/logout',{method:'POST',headers:headers(true)})}catch{}save(null);favSet.clear();closeM();await load()}
async function adminCheck(){isAdmin=false;if(!session)return;try{const d=await req("/rest/v1/admins?select=user_id&user_id=eq."+session.user.id,{headers:headers(true)});isAdmin=d.length>0}catch{}}
let page=0,loadVersion=0;const PAGE_SIZE=24;
function normalizeCars(d){return d.map(x=>({...x,images:(x.listing_images||[]).sort((a,b)=>a.position-b.position).map(i=>/^https?:\/\//i.test(i.storage_path)?i.storage_path:i.storage_path.endsWith('/__test_placeholder__')?'/test-car.svg':URL+"/storage/v1/object/public/listing-photos/"+i.storage_path.split('/').map(encodeURIComponent).join('/'))}))}
function resetFilters(){for(const id of ['make','model','city','pmin','pmax','ymin','ymax','fuel','transmission','drivetrain','engine'])$(id).value='';$('make').onchange();$('km').value=500000;$('km').oninput();load()}
async function load(next=0){const version=++loadVersion;page=next;view="home";$("title").textContent="Cars for sale";$("count").textContent="Loading…";$("pages").replaceChildren();if($("sortWrap"))$("sortWrap").hidden=false;
 const sortValue=$("sort")?.value||"recent",sortOrders={recent:"created_at.desc,id.desc",price_asc:"price.asc,id.desc",price_desc:"price.desc,id.desc",year_desc:"year.desc,created_at.desc,id.desc",year_asc:"year.asc,created_at.desc,id.desc",mileage_asc:"mileage.asc,id.desc"},order=sortOrders[sortValue]||sortOrders.recent;
 let q="/rest/v1/listings?select=*,listing_images(storage_path,position)&status=eq.active&order="+encodeURIComponent(order)+"&limit="+(PAGE_SIZE+1)+"&offset="+(page*PAGE_SIZE);
 for(const field of ['make','model','city','fuel','transmission','drivetrain','engine'])if($(field).value)q+='&'+field+'=eq.'+encodeURIComponent($(field).value);
 try{for(const [field,min,max] of [['price','pmin','pmax'],['year','ymin','ymax']]){const lo=$(min).value,hi=$(max).value;if((lo&&(!Number.isFinite(+lo)||+lo<0))||(hi&&(!Number.isFinite(+hi)||+hi<0))||(lo&&hi&&+lo>+hi))throw new Error('Check the '+field+' range.');if(lo)q+='&'+field+'=gte.'+lo;if(hi)q+='&'+field+'=lte.'+hi}
 if(+$('km').value<500000)q+='&mileage=lte.'+$('km').value;
 const d=await req(q,{headers:headers(false)});await loadFavs();if(version!==loadVersion)return;cars=normalizeCars(d.slice(0,PAGE_SIZE));render(cars);setListingCount(cars.length,page);$('pages').innerHTML=(page?'<button class="secondary" onclick="load(page-1)">Previous</button>':'')+(d.length>PAGE_SIZE?'<button class="secondary" onclick="load(page+1)">Next</button>':'');
 }catch(e){if(version!==loadVersion)return;cars=[];$('count').textContent=e.message;$('cards').innerHTML='<div class="empty">Could not load listings. Please check the filters or try again.</div>'}}
async function loadFavs(){favSet=new Set();if(!session)return;try{const d=await req("/rest/v1/favorites?select=listing_id",{headers:headers(true)});d.forEach(x=>favSet.add(x.listing_id))}catch{}}
function nextFrame(fn){if(typeof requestAnimationFrame==="function")requestAnimationFrame(fn);else fn()}
function enhanceCards(){const cards=[...document.querySelectorAll("#cards .card")];cards.forEach((card,i)=>{card.style?.setProperty?.("--delay",Math.min(i,8)*45+"ms");nextFrame(()=>card.classList.add("card-in"));const img=card.querySelector?.(".photo");if(img){const ready=()=>img.classList.add("photo-ready");if(img.complete)ready();else img.addEventListener("load",ready,{once:true})}})}
function setListingCount(n,pageNumber){const el=$("count");if(!el)return;const end=Math.max(0,Number(n)||0);if(typeof requestAnimationFrame!=="function"){el.textContent=end+" listings · page "+(pageNumber+1);return}const started=Date.now(),duration=280;function frame(){const p=Math.min(1,(Date.now()-started)/duration),value=Math.round(end*(1-Math.pow(1-p,3)));el.textContent=value+" listings · page "+(pageNumber+1);if(p<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function initMicroInteractions(){document.addEventListener("pointerdown",e=>{const el=e.target.closest(".primary,.secondary,.search,.sell,.auth");if(!el||el.disabled)return;const r=el.getBoundingClientRect(),dot=document.createElement("span");dot.className="tap-ripple";dot.style.left=(e.clientX-r.left)+"px";dot.style.top=(e.clientY-r.top)+"px";el.appendChild(dot);setTimeout(()=>dot.remove(),520)});document.querySelectorAll(".field,.money input,#sort").forEach(el=>el.addEventListener("change",()=>{const box=el.closest(".searchbox,.sorter");if(!box)return;box.classList.remove("ui-pulse");requestAnimationFrame(()=>box.classList.add("ui-pulse"));setTimeout(()=>box.classList.remove("ui-pulse"),420)}))}
function heartIcon(on){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 5.7c-1.7-2-4.8-2.1-6.7-.2L12 7.6 9.9 5.5C8 3.6 4.9 3.7 3.2 5.7c-1.6 1.9-1.4 4.7.4 6.5L12 20l8.4-7.8c1.8-1.8 2-4.6.4-6.5z"/></svg>'}
function listedAgo(value){if(!value)return "";const ms=Date.now()-new Date(value).getTime();if(!Number.isFinite(ms)||ms<0)return "";const days=Math.floor(ms/86400000);if(days<1)return "Listed today";if(days===1)return "Listed 1 day ago";if(days<30)return "Listed "+days+" days ago";const months=Math.floor(days/30);return "Listed "+months+" month"+(months===1?"":"s")+" ago"}
function render(list){$("cards").innerHTML=list.length?list.map(c=>{const on=favSet.has(c.id),engine=c.engine?" · "+esc(c.engine):"",drive=c.drivetrain?'<span class="cardchip">'+esc(c.drivetrain)+'</span>':"",listed=listedAgo(c.created_at);return '<article class="card"><div class="photo-wrap"><img loading="lazy" alt="Vehicle photo" class="photo clickable-photo" src="'+(c.images[0]||'')+'" onclick="detail(\''+c.id+'\',0)" onerror="this.style.display=\'none\'"><span class="private-badge">Private seller</span><button aria-label="'+(on?"Remove from favorites":"Add to favorites")+'" class="fav '+(on?'on':'')+'" onclick="toggleFav(\''+c.id+'\',event)">'+heartIcon(on)+'</button></div><button class="body" onclick="detail(\''+c.id+'\',0)"><div class="name">'+c.year+' '+esc(c.make)+' '+esc(c.model)+'</div><div class="price">$ '+Number(c.price).toLocaleString()+' CAD</div><div class="specgrid"><div><span class="specicon">◔</span>'+Number(c.mileage).toLocaleString()+' km</div><div><span class="specicon">⚙</span>'+esc(c.transmission||"Transmission n/a")+'</div><div><span class="specicon">◇</span>'+esc(c.fuel)+engine+'</div><div><span class="specicon">⌖</span>'+esc(c.city||"Alberta")+'</div></div><div class="cardchips"><span class="cardchip soft">Alberta</span>'+drive+'</div>'+(listed?'<div class="listed">'+listed+'</div>':'')+'</button></article>'}).join(""):'<div class="empty">No listings yet. Add the first car.</div>';enhanceCards()}
async function toggleFav(id,e){e.stopPropagation();if(!session)return auth();try{if(favSet.has(id)){await req("/rest/v1/favorites?listing_id=eq."+id,{method:"DELETE",headers:headers(true)});favSet.delete(id)}else{await req("/rest/v1/favorites",{method:"POST",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({user_id:session.user.id,listing_id:id})});favSet.add(id)}const source=e?.currentTarget;if(source){source.classList.add("fav-pop");setTimeout(()=>source.classList.remove("fav-pop"),320)}setTimeout(()=>{view==="fav"?favorites():render(cars)},130)}catch(e){alert(e.message)}}
let galleryImages=[],galleryIndex=0;
function setGalleryImage(index){if(!galleryImages.length)return;galleryIndex=(index+galleryImages.length)%galleryImages.length;const main=$("galleryMain");if(main){main.classList.add("photo-switch");const done=()=>main.classList.remove("photo-switch");main.addEventListener("load",done,{once:true});main.src=galleryImages[galleryIndex];setTimeout(done,450)}document.querySelectorAll(".gallerythumb").forEach((el,i)=>el.classList.toggle("active",i===galleryIndex));const active=document.querySelector(".gallerythumb.active");active?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})}
function galleryStep(delta){setGalleryImage(galleryIndex+delta)}
async function detail(id,startIndex=0){let c=cars.find(x=>x.id===id);if(!c&&isAdmin){try{const d=await req('/rest/v1/listings?select=*,listing_images(storage_path,position)&id=eq.'+encodeURIComponent(id),{headers:headers(true)});c=normalizeCars(d)[0]}catch(e){alert(e.message);return}}if(!c)return;try{if(session)await req("/rest/v1/listing_views",{method:"POST",headers:{...headers(!!session),Prefer:"return=minimal"},body:JSON.stringify({listing_id:id,viewer_id:session?.user?.id||null})})}catch{}galleryImages=c.images||[];galleryIndex=Math.max(0,Math.min(Number(startIndex)||0,Math.max(0,galleryImages.length-1)));const gallery=galleryImages.length?'<div class="viewer"><button class="gallerynav prev" aria-label="Previous photo" onclick="galleryStep(-1)">‹</button><img id="galleryMain" class="detail" alt="Vehicle photo" src="'+esc(galleryImages[galleryIndex])+'"><button class="gallerynav next" aria-label="Next photo" onclick="galleryStep(1)">›</button></div><div class="gallery">'+galleryImages.map((src,i)=>'<button class="gallerythumb '+(i===galleryIndex?'active':'')+'" type="button" onclick="setGalleryImage('+i+')" aria-label="View photo '+(i+1)+'"><img alt="Vehicle photo '+(i+1)+'" loading="lazy" src="'+esc(src)+'"></button>').join('')+'</div>':'';show('<div class="detailbar"><button class="backresults" type="button" onclick="closeM()">← Back to results</button><button class="close detailclose" type="button" onclick="closeM()" aria-label="Close">×</button></div>'+gallery+'<div class="modalbody"><h2>'+c.year+' '+esc(c.make)+' '+esc(c.model)+'</h2><div class="price">$ '+Number(c.price).toLocaleString()+' CAD</div><div class="dgrid"><div class="d">Mileage<b>'+Number(c.mileage).toLocaleString()+' km</b></div><div class="d">City<b>'+esc(c.city||'Alberta')+'</b></div><div class="d">Fuel<b>'+esc(c.fuel)+'</b></div>'+(c.transmission?'<div class="d">Transmission<b>'+esc(c.transmission)+'</b></div>':'')+(c.drivetrain?'<div class="d">Drivetrain<b>'+esc(c.drivetrain)+'</b></div>':'')+(c.engine?'<div class="d">Engine<b>'+esc(c.engine)+'</b></div>':'')+'</div><p>'+esc(c.description||'')+'</p><div class="actions">'+(c.seller_phone?'<a class="primary" href="tel:'+esc(c.seller_phone.replace(/[^+0-9]/g,''))+'">Call seller</a>':'')+(c.seller_email?'<a class="secondary" href="mailto:'+esc(c.seller_email)+'">Email</a>':'')+(c.seller_telegram?'<a class="secondary" target="_blank" rel="noopener noreferrer" href="https://t.me/'+encodeURIComponent(c.seller_telegram.replace(/^@/,''))+'">Telegram</a>':'')+'<button class="secondary" onclick="reportListing(\''+c.id+'\')">Report listing</button></div></div>')}
let authMode="signin";
function auth(){if(session)return signout();authMode="signin";show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2 id="authTitle">Sign in</h2><p id="authHint" class="authhint">Use your email and password to access your account.</p><form id="authForm" onsubmit="event.preventDefault();authMode===\'signup\'?signup():signin()"><label>Email<input id="ae" class="input" type="email" required autocomplete="email"></label><label>Password<input id="ap" class="input" type="password" required minlength="8" autocomplete="current-password"></label><div class="actions authactions"><button id="loginSubmit" class="primary" type="button" onclick="signin()">Sign in</button><button id="signupSubmit" class="secondary" type="button" onclick="signup()">Create account</button><button class="secondary" type="button" onclick="forgotPassword()">Forgot password?</button></div><p>By creating an account you agree to the <a href="/terms.html" target="_blank" rel="noopener">Terms</a> and <a href="/privacy.html" target="_blank" rel="noopener">Privacy Policy</a>.</p><div id="amsg" role="status"></div></form></div>')}
function setAuthMode(mode){authMode=mode;const login=$("loginSubmit"),signup=$("signupSubmit"),title=$("authTitle"),hint=$("authHint");if(login){login.className=mode==="signin"?"primary":"secondary"}if(signup){signup.className=mode==="signup"?"primary":"secondary"}if(title)title.textContent=mode==="signup"?"Create account":"Sign in";if(hint)hint.textContent=mode==="signup"?"Create your P2PCars account with email and password.":"Use your email and password to access your account."}
let authBusy=false;
function authErrorMessage(message){
  const m=String(message||"");
  if(/email rate limit exceeded|rate limit/i.test(m))return "Too many email requests. Please wait a minute and try again.";
  if(/invalid login credentials/i.test(m))return "Incorrect email or password.";
  if(/email address not authorized/i.test(m))return "Email delivery is not configured for public signups yet.";
  return m;
}
function startCooldown(button,seconds=60){
  if(!button)return;
  const original=button.textContent;
  let left=seconds;
  button.disabled=true;
  const tick=()=>{button.textContent=left>0?original+" ("+left+"s)":original;if(left--<=0){clearInterval(timer);button.disabled=false;button.textContent=original}};
  tick();const timer=setInterval(tick,1000);
}
async function authenticate(create){if(authBusy||!$('authForm').reportValidity())return;authBusy=true;try{const email=$('ae').value.trim(),password=$('ap').value;const body={email,password};if(create)body.data={display_name:email.split('@')[0]};const d=await req(create?'/auth/v1/signup?redirect_to='+encodeURIComponent(location.origin+'/'):'/auth/v1/token?grant_type=password',{method:'POST',headers:headers(false),body:JSON.stringify(body)});if(d.access_token){save({...d,expires_at:Math.floor(Date.now()/1000)+d.expires_in});await adminCheck();closeM();await load()}else{message('amsg','Check your email for a confirmation link, then sign in.',true);if(create)startCooldown(document.querySelector('[onclick="signup()"]'),60)}}catch(e){message('amsg',authErrorMessage(e.message))}finally{authBusy=false}}
function signin(){setAuthMode("signin");return authenticate(false)}function signup(){setAuthMode("signup");return authenticate(true)}
function forgotPassword(){show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>Reset password</h2><form onsubmit="event.preventDefault();sendRecovery()"><label>Email<input id="re" class="input" type="email" required autocomplete="email"></label><button id="recover" class="primary" type="submit">Send reset link</button><div id="rmsg" role="status"></div></form></div>')}
async function sendRecovery(){const button=$('recover');button.disabled=true;try{await req('/auth/v1/recover?redirect_to='+encodeURIComponent(location.origin+'/'),{method:'POST',headers:headers(false),body:JSON.stringify({email:$('re').value.trim()})});message('rmsg','If this email has an account, a reset link will arrive shortly.',true);startCooldown(button,60)}catch(e){message('rmsg',authErrorMessage(e.message));button.disabled=false}}
function recoveryForm(){show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>Choose a new password</h2><form onsubmit="event.preventDefault();updatePassword()"><label>New password<input id="rp" class="input" type="password" minlength="8" required autocomplete="new-password"></label><label>Confirm password<input id="rp2" class="input" type="password" minlength="8" required autocomplete="new-password"></label><button id="reset" class="primary">Save password</button><div id="rmsg" role="status"></div></form></div>')}
async function updatePassword(){if($('rp').value!==$('rp2').value)return message('rmsg','Passwords must match.');const b=$('reset');b.disabled=true;try{await req('/auth/v1/user',{method:'PUT',headers:headers(true),body:JSON.stringify({password:$('rp').value})});message('rmsg','Password updated. You are signed in.',true);await adminCheck();setTimeout(()=>{closeM();account()},500)}catch(e){message('rmsg',e.message);b.disabled=false}}
async function authCallback(){const p=new URLSearchParams(location.hash.slice(1));if(!p.has('access_token')&&!p.has('error_description'))return false;history.replaceState(null,'',location.pathname);if(p.has('error_description')){show('<div class="modalbody"><h2>Sign-in link</h2><p>'+esc(p.get('error_description'))+'</p><button class="secondary" onclick="auth()">Sign in</button></div>');return true}const access=p.get('access_token');try{const user=await req('/auth/v1/user',{headers:{...headers(false),Authorization:'Bearer '+access}});save({access_token:access,refresh_token:p.get('refresh_token'),expires_at:Math.floor(Date.now()/1000)+Number(p.get('expires_in')||3600),user});await adminCheck();if(p.get('type')==='recovery'){recoveryForm();return true}}catch(e){save(null);show('<div class="modalbody"><p>'+esc(e.message)+'</p></div>');return true}return false}
function sell(){if(!session)return auth();show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>Sell your car</h2><form onsubmit="postCar(event)"><div class="formgrid"><select id="sm" class="input" required><option value="">Make *</option>'+Object.keys(makes).sort().map(x=>'<option>'+x+'</option>').join("")+'</select><select id="smo" class="input" required><option value="">Model *</option></select><input id="sy" class="input" type="number" min="1980" max="2100" placeholder="Year *" required><input id="sp" class="input" type="number" min="500" max="2000000" placeholder="Price CAD *" required><input id="sk" class="input" type="number" min="0" max="2000000" placeholder="Mileage km *" required><select id="sf" class="input" required><option value="">Fuel *</option><option>Gasoline</option><option>Diesel</option><option>Hybrid</option><option>Plug-in Hybrid</option><option>Electric</option></select><select id="str" class="input"><option value="">Transmission</option><option>Automatic</option><option>Manual</option><option>CVT</option><option>DCT</option></select><select id="sdt" class="input"><option value="">Drivetrain</option><option>FWD</option><option>RWD</option><option>AWD</option><option>4WD</option></select><select id="sen" class="input"><option value="">Engine size</option><option>1.0 L</option><option>1.2 L</option><option>1.3 L</option><option>1.4 L</option><option>1.5 L</option><option>1.6 L</option><option>1.8 L</option><option>2.0 L</option><option>2.2 L</option><option>2.3 L</option><option>2.4 L</option><option>2.5 L</option><option>2.7 L</option><option>3.0 L</option><option>3.3 L</option><option>3.5 L</option><option>3.6 L</option><option>3.8 L</option><option>4.0 L</option><option>4.4 L</option><option>4.6 L</option><option>5.0 L</option><option>5.3 L</option><option>5.7 L</option><option>6.2 L</option><option>6.4 L</option><option>6.6 L</option><option>6.7 L</option></select><select id="sc" class="input"><option value="">City</option><option>Calgary</option><option>Edmonton</option><option>Red Deer</option><option>Lethbridge</option><option>Airdrie</option><option>Okotoks</option></select><input id="sph" class="input" placeholder="Phone"><input id="se" class="input" type="email" value="'+esc(session.user.email||"")+'" placeholder="Email"><input id="stg" class="input" placeholder="Telegram @username"><textarea id="sd" class="input full" rows="4" maxlength="3000" placeholder="Description"></textarea><label class="full">Photos * (1–8)<input id="si" class="input" type="file" accept="image/jpeg,image/png,image/webp" multiple required></label></div><div class="actions"><button id="post" class="primary" type="submit">Submit for review</button></div><div id="smsg"></div></form></div>');$("sm").onchange=()=>{$("smo").innerHTML='<option value="">Model *</option>'+((makes[$("sm").value]||[]).map(x=>'<option>'+x+'</option>').join(""))}}
async function postCar(e){e.preventDefault();const b=$("post");if(b.disabled)return;b.disabled=true;b.textContent="Uploading…";let listingId=null,uploaded=[];try{const fs=[...$("si").files];if(fs.length<1||fs.length>8)throw new Error("Choose 1–8 photos.");for(const f of fs)if(!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>8*1024*1024||!f.size)throw new Error("Choose JPEG, PNG or WebP photos under 8 MB.");const phone=$("sph").value.trim(),email=$("se").value.trim(),tg=$("stg").value.trim();if(!phone&&!email&&!tg)throw new Error("Add phone, email or Telegram.");const payload={user_id:session.user.id,seller_name:session.user.user_metadata?.display_name||session.user.email,seller_phone:phone||null,seller_email:email||null,seller_telegram:tg||null,make:$("sm").value,model:$("smo").value,year:+$("sy").value,price:+$("sp").value,mileage:+$("sk").value,fuel:$("sf").value,transmission:$("str").value||null,drivetrain:$("sdt").value||null,engine:$("sen").value||null,city:$("sc").value||null,description:$("sd").value||null,features:[],status:"pending"};const listing=await req("/rest/v1/listings",{method:"POST",headers:{...headers(true),Prefer:"return=representation"},body:JSON.stringify(payload)});const l=listing[0];listingId=l.id;const rows=[];for(let i=0;i<fs.length;i++){const f=fs[i];if(f.size>8*1024*1024)throw new Error("Each photo must be under 8 MB.");const ext=f.type==="image/png"?"png":f.type==="image/webp"?"webp":"jpg",path=session.user.id+"/"+l.id+"/"+crypto.randomUUID()+"."+ext;const r=await fetch(URL+"/storage/v1/object/listing-photos/"+path,{signal:AbortSignal.timeout(60000),method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+session.access_token,"Content-Type":f.type,"x-upsert":"false"},body:f});if(!r.ok){let x={};try{x=await r.json()}catch{}throw new Error(x.message||"Photo upload failed")}uploaded.push(path);rows.push({listing_id:l.id,storage_path:path,position:i})}await req("/rest/v1/listing_images",{method:"POST",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify(rows)});$("smsg").innerHTML='<div class="msg ok">Submitted for review. Your car appears after admin approval.</div>';b.textContent="Submitted";b.disabled=true;await load()}catch(e){if(uploaded.length)try{await fetch(URL+"/storage/v1/object/listing-photos",{method:"DELETE",headers:headers(true),body:JSON.stringify({prefixes:uploaded})})}catch{};if(listingId)try{await req("/rest/v1/listings?id=eq."+listingId,{method:"DELETE",headers:headers(true)})}catch{};listingId=null;$("smsg").innerHTML='<div class="msg err">'+esc(e.message)+'</div>'}finally{if(!listingId){b.disabled=false;b.textContent="Submit for review"}}}
async function reportListing(id){if(!session)return auth();const reason=prompt("Reason for report (scam, dealer, incorrect info, sold, other):");if(!reason)return;try{await req("/rest/v1/listing_reports",{method:"POST",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({listing_id:id,reporter_id:session.user.id,reason:reason.slice(0,120)})});alert("Report submitted. Thank you.")}catch(e){alert(e.message.includes("duplicate")?"You already reported this listing.":e.message)}}
async function favorites(){if(!session)return auth();const version=++loadVersion;view="fav";page=0;$('pages').replaceChildren();$('title').textContent='Favorites';$('count').textContent='Loading…';if($("sortWrap"))$("sortWrap").hidden=true;try{const d=await req('/rest/v1/favorites?select=listings!inner(*,listing_images(storage_path,position))&listings.status=eq.active&order=created_at.desc&limit=100',{headers:headers(true)});await loadFavs();if(version!==loadVersion)return;cars=normalizeCars(d.map(x=>x.listings));render(cars);$('count').textContent=cars.length+' saved'+(cars.length===100?' (latest 100)':'')}catch(e){$('count').textContent=e.message;render([])}}
async function account(){if(!session)return auth();await adminCheck();try{const d=await req("/rest/v1/listings?select=id,make,model,year,price,status&user_id=eq."+session.user.id+"&order=created_at.desc",{headers:headers(true)});show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>My account</h2><p><b>'+esc(session.user.user_metadata?.display_name||"User")+'</b><br>'+esc(session.user.email)+'</p><button class="primary" onclick="sell()">Post my car</button>'+(isAdmin?'<button class="secondary" onclick="fullAdmin(\'dashboard\')">Admin panel</button>':'')+'<button class="secondary" onclick="signout()">Sign out</button><h3>My listings</h3>'+(d.length?d.map(x=>'<div class="row"><div><b>'+x.year+' '+esc(x.make)+' '+esc(x.model)+'</b><br><small>$'+Number(x.price).toLocaleString()+' · '+esc(x.status)+'</small></div><div><button class="secondary" onclick="markStatus(\''+x.id+'\',\'sold\')">Sold</button> <button class="secondary" onclick="markStatus(\''+x.id+'\',\'removed\')">Remove</button></div></div>').join(""):'<p>No listings yet.</p>')+'</div>')}catch(e){alert(e.message)}}
async function markStatus(id,status){try{await req("/rest/v1/listings?id=eq."+id,{method:"PATCH",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({status})});account();load()}catch(e){alert(e.message)}}
async function adminPanel(){return fullAdmin("dashboard")}
async function fullAdmin(tab="dashboard"){
 if(!isAdmin)return alert("Admin access required");
 try{
   if(tab==="dashboard"){
     const st=await req("/rest/v1/rpc/admin_dashboard_stats",{method:"POST",headers:headers(true),body:"{}"});
     show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>P2PCars Admin</h2>'+adminTabs("dashboard")+'<div class="dgrid"><div class="d">Users<b>'+st.users+'</b></div><div class="d">Active listings<b>'+st.activeListings+'</b></div><div class="d">All listings<b>'+st.listings+'</b></div><div class="d">Open reports<b>'+st.openReports+'</b></div><div class="d">Listing views<b>'+st.views+'</b></div><div class="d">Blocked users<b>'+st.blockedUsers+'</b></div></div></div>');
   } else if(tab==="users"){
     const users=await req("/rest/v1/rpc/admin_users",{method:"POST",headers:headers(true),body:"{}"});
     window._adminUsers=users;
     show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>P2PCars Admin</h2>'+adminTabs("users")+'<input id="userSearch" class="input" placeholder="Search users by email or name" oninput="filterAdminUsers()"><div id="adminUsersList">'+renderAdminUsers(users)+'</div></div>');
   } else if(tab==="listings"){
     const listings=await req("/rest/v1/listings?select=id,user_id,make,model,year,price,status,seller_name,created_at&order=created_at.desc&limit=200",{headers:headers(true)});
     show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>P2PCars Admin</h2>'+adminTabs("listings")+(listings.length?listings.map(x=>'<div class="row"><div><b>'+x.year+' '+esc(x.make)+' '+esc(x.model)+'</b><br><small>'+esc(x.seller_name)+' · $'+Number(x.price).toLocaleString()+' · '+esc(x.status)+'</small></div><div><button class="secondary" onclick="detail(\''+x.id+'\')">Preview</button> <button class="secondary" onclick="adminSetListingStatus(\''+x.id+'\',\'active\')">Activate</button> <button class="danger" onclick="adminSetListingStatus(\''+x.id+'\',\'removed\')">Remove</button></div></div>').join(""):'<p>No listings.</p>')+'</div>');
   } else if(tab==="reports"){
     const reports=await req("/rest/v1/listing_reports?select=*&order=created_at.desc&limit=200",{headers:headers(true)});
     show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>P2PCars Admin</h2>'+adminTabs("reports")+(reports.length?reports.map(r=>'<div class="row"><div><b>'+esc(r.reason)+'</b><br><small>Listing '+r.listing_id+' · '+esc(r.status)+'</small></div><div><button class="secondary" onclick="setReportStatus('+r.id+',\'reviewed\')">Reviewed</button> <button class="secondary" onclick="setReportStatus('+r.id+',\'dismissed\')">Dismiss</button> <button class="danger" onclick="adminSetListingStatus(\''+r.listing_id+'\',\'removed\')">Remove listing</button></div></div>').join(""):'<p>No reports.</p>')+'</div>');
   } else if(tab==="analytics"){
     const st=await req("/rest/v1/rpc/admin_dashboard_stats",{method:"POST",headers:headers(true),body:"{}"});
     const ev=await req("/rest/v1/site_events?select=event_name,created_at&order=created_at.desc&limit=100",{headers:headers(true)});
     show('<button class="close" onclick="closeM()">×</button><div class="modalbody"><h2>P2PCars Admin</h2>'+adminTabs("analytics")+'<div class="dgrid"><div class="d">Users<b>'+st.users+'</b></div><div class="d">Page events<b>'+st.events+'</b></div><div class="d">Listing views<b>'+st.views+'</b></div></div><h3>Recent activity</h3>'+(ev.length?ev.slice(0,30).map(e=>'<div class="row"><div><b>'+esc(e.event_name)+'</b><br><small>'+new Date(e.created_at).toLocaleString()+'</small></div></div>').join(""):'<p>No activity yet.</p>')+'</div>');
   }
 }catch(e){alert(e.message)}
}
function adminTabs(active){return '<div class="actions" style="margin-bottom:15px">'+["dashboard","users","listings","reports","analytics"].map(t=>'<button class="'+(t===active?'primary':'secondary')+'" onclick="fullAdmin(\''+t+'\')">'+t[0].toUpperCase()+t.slice(1)+'</button>').join("")+'</div>'}
function renderAdminUsers(users){return users.length?users.map(u=>'<div class="row"><div><b>'+esc(u.display_name||"User")+'</b><br><small>'+esc(u.email)+' · '+u.listings_count+' listings · '+u.reports_received+' reports'+(u.is_blocked?' · BLOCKED':'')+'</small></div><div><button class="secondary" onclick="showUserListings(\''+u.user_id+'\')">Listings</button> '+(u.is_blocked?'<button class="secondary" onclick="setUserBlock(\''+u.user_id+'\',false)">Unblock</button>':'<button class="danger" onclick="setUserBlock(\''+u.user_id+'\',true)">Block</button>')+'</div></div>').join(""):'<p>No users.</p>'}
function filterAdminUsers(){const q=($("userSearch").value||"").toLowerCase();const users=(window._adminUsers||[]).filter(u=>(u.email||"").toLowerCase().includes(q)||(u.display_name||"").toLowerCase().includes(q));$("adminUsersList").innerHTML=renderAdminUsers(users)}
async function setUserBlock(id,blocked){let reason=null;if(blocked){reason=prompt("Reason for blocking this user:","Marketplace policy violation");if(reason===null)return}try{await req("/rest/v1/rpc/admin_set_user_block",{method:"POST",headers:headers(true),body:JSON.stringify({target_user:id,blocked,block_reason:reason,until_time:null})});fullAdmin("users");load()}catch(e){alert(e.message)}}
async function showUserListings(uid){try{const d=await req("/rest/v1/listings?select=id,make,model,year,price,status,created_at&user_id=eq."+uid+"&order=created_at.desc",{headers:headers(true)});show('<button class="close" onclick="fullAdmin(\'users\')">×</button><div class="modalbody"><h2>User listings</h2>'+(d.length?d.map(x=>'<div class="row"><div><b>'+x.year+' '+esc(x.make)+' '+esc(x.model)+'</b><br><small>$'+Number(x.price).toLocaleString()+' · '+esc(x.status)+'</small></div><div><button class="secondary" onclick="detail(\''+x.id+'\')">Preview</button> <button class="secondary" onclick="adminSetListingStatus(\''+x.id+'\',\'active\')">Activate</button> <button class="danger" onclick="adminSetListingStatus(\''+x.id+'\',\'removed\')">Remove</button></div></div>').join(""):'<p>No listings.</p>')+'</div>')}catch(e){alert(e.message)}}
async function adminSetListingStatus(id,status){try{await req("/rest/v1/listings?id=eq."+id,{method:"PATCH",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({status})});load();fullAdmin("listings")}catch(e){alert(e.message)}}
async function setReportStatus(id,status){try{await req("/rest/v1/listing_reports?id=eq."+id,{method:"PATCH",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({status})});fullAdmin("reports")}catch(e){alert(e.message)}}
async function reviewReport(id){try{await req("/rest/v1/listing_reports?id=eq."+id,{method:"PATCH",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({status:"reviewed"})});adminPanel()}catch(e){alert(e.message)}}
async function adminRemove(id){if(!confirm("Remove this listing from public view?"))return;try{await req("/rest/v1/listings?id=eq."+id,{method:"PATCH",headers:{...headers(true),Prefer:"return=minimal"},body:JSON.stringify({status:"removed"})});adminPanel();load()}catch(e){alert(e.message)}}
function home(){closeM();load()}function nav(el){document.querySelectorAll('.mobile button').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
let previousFocus=null;
function show(h){previousFocus=document.activeElement;$('modal').innerHTML=h;$('modal').classList.remove('modal-ready');$('mbg').classList.add('show');nextFrame(()=>nextFrame(()=>$('modal').classList.add('modal-ready')));document.body.style.overflow='hidden';$('modal').querySelectorAll('input,select,textarea').forEach(el=>{if(!el.getAttribute('aria-label'))el.setAttribute('aria-label',el.getAttribute('placeholder')||el.options?.[0]?.text||el.type)});$('modal').querySelectorAll('.close').forEach(el=>el.setAttribute('aria-label','Close'));$('modal').focus()}
function closeM(){if($('post')?.textContent==='Uploading…')return;$('mbg').classList.remove('show');document.body.style.overflow='';previousFocus?.focus()}
document.addEventListener('keydown',e=>{if(!$('mbg').classList.contains('show'))return;if(e.key==='Escape')closeM();if(e.key==='Tab'){const els=[...$('modal').querySelectorAll('button,a,input,select,textarea,[tabindex]')].filter(el=>!el.disabled&&el.offsetParent!==null);if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('modal'))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===$('modal'))){e.preventDefault();first.focus()}}});
async function track(name){if(!session)return;try{await req("/rest/v1/site_events",{method:"POST",headers:{...headers(!!session),Prefer:"return=minimal"},body:JSON.stringify({event_name:name,user_id:session?.user?.id||null,path:location.pathname})})}catch{}}
(async()=>{save(session);initMicroInteractions();try{await authCallback();if(session?.expires_at<Date.now()/1000+60)await refreshSession();await adminCheck()}catch(e){console.error('Authentication initialization failed');}track("page_view");await load()})();

let errorRecorded=false;function recordClientError(){if(errorRecorded)return;errorRecorded=true;track("client_error")}window.addEventListener("error",recordClientError);window.addEventListener("unhandledrejection",recordClientError);
