-- Production features added on 2026-09-06.
-- Keeps admin moderation, reports and lightweight analytics reproducible.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admins enable row level security;

create table if not exists public.listing_reports (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 120),
  details text null check (details is null or char_length(details) <= 1000),
  status text not null default 'open' check (status in ('open','reviewed','dismissed')),
  created_at timestamptz not null default now(),
  unique (listing_id, reporter_id)
);

create table if not exists public.listing_views (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  viewer_id uuid null references auth.users(id) on delete set null,
  viewed_at timestamptz not null default now()
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (char_length(event_name) between 2 and 80),
  user_id uuid null references auth.users(id) on delete set null,
  path text null check (path is null or char_length(path) <= 500),
  created_at timestamptz not null default now()
);

create index if not exists idx_listing_reports_listing on public.listing_reports(listing_id);
create index if not exists idx_listing_reports_reporter on public.listing_reports(reporter_id);
create index if not exists idx_listing_reports_status on public.listing_reports(status);
create index if not exists idx_listing_views_listing on public.listing_views(listing_id);
create index if not exists idx_listing_views_viewer on public.listing_views(viewer_id);
create index if not exists idx_listing_views_viewed_at on public.listing_views(viewed_at desc);
create index if not exists idx_site_events_created_at on public.site_events(created_at desc);
create index if not exists idx_site_events_event_name on public.site_events(event_name);
create index if not exists idx_site_events_user on public.site_events(user_id);

alter function private.enforce_private_listing_insert() set search_path = pg_catalog, public, private;
